apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccloud-exporter
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccloud-exporter
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2112"
      labels:
        app: ccloud-exporter
    spec:
      containers:
        - name: ccloudexporter
          image: dabz/ccloudexporter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 2112
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30